src/AppBundle/Entity/Project.php
<?php

declare(strict_types=1);

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity()
 * @ORM\Table()
 */
class Project
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="User", cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * @Assert\Valid()
     */
    private $user;

    /**
     * @Assert\NotBlank(message="Pasirinkite priemonę")
     */
    private $measure;

    /**
     * @ORM\OneToMany(
     *     targetEntity="ProjectMeasureValue",
     *     mappedBy="project",
     *     cascade={"persist"}
     * )
     * @Assert\Valid()
     */
    private $projectMeasureValues;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="Pasirinkite pildymo datą")
     */
    private $createdAt;

    public function __construct()
    {
        $this->projectMeasureValues = new ArrayCollection();
    }

    public function getQrCode(): string
    {
        return sprintf('%s', $this->getId());
    }

    public function getTotalRate()
    {
        $total = 0;

        foreach ($this->getProjectMeasureValues() as $measure) {
            $total += $measure->getRate();
        }

        return $total;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    public function getMeasure(): ?Measure
    {
        return $this->measure;
    }

    public function setMeasure(Measure $measure)
    {
        $this->measure = $measure;
    }

    public function getProjectMeasureValues(): ?Collection
    {
        return $this->projectMeasureValues;
    }

    public function addProjectMeasureValue(ProjectMeasureValue $projectMeasureValue)
    {
        $projectMeasureValue->setProject($this);
        $this->projectMeasureValues->add($projectMeasureValue);
    }

    public function clearProjectMeasureValues()
    {
        $this->projectMeasureValues->clear();
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }
}

src/AppBundle/Entity/ProjectMeasureValue.php
<?php

declare(strict_types=1);

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity()
 * @ORM\Table()
 */
class ProjectMeasureValue
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="Įveskite priemonės apimtį")
     */
    private $value;

    /**
     * @ORM\ManyToOne(targetEntity="MeasureValue")
     * @ORM\JoinColumn(name="measure_value_id", referencedColumnName="id")
     */
    private $measureValue;

    /**
     * @ORM\ManyToOne(targetEntity="project")
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     */
    private $project;

    public function __construct(MeasureValue $measureValue)
    {
        $this->measureValue = $measureValue;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->getMeasureValue()->getName();
    }

    public function getRate(): int
    {
        return $this->getMeasureValue()->getRate();
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value)
    {
        $this->value = $value;
    }

    public function getMeasureValue(): ?MeasureValue
    {
        return $this->measureValue;
    }

    public function setMeasureValue(MeasureValue $measureValue)
    {
        $this->measureValue = $measureValue;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(Project $project)
    {
        $this->project = $project;
    }
}

src/AppBundle/Form/ProjectType.php
<?php

declare(strict_types=1);

namespace AppBundle\Form;

use AppBundle\Entity\Measure;
use AppBundle\Entity\Project;
use AppBundle\Entity\ProjectMeasureValue;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user', UserType::class)
            ->add('measure', EntityType::class, array(
                'class' => Measure::class,
                'label' => 'Priemonė',
                'placeholder' => '',
            ))
            ->add('createdAt', DateType::class, [
                'label' => 'Pildymo data',
                'data' => new \DateTime(),
                'widget' => 'single_text',
            ])
        ;

        $formModifier = function (FormInterface $form) {
            $form->add('projectMeasureValues', CollectionType::class, [
                'entry_type' => ProjectMeasureValueType::class,
                'label' => false,
            ]);
        };

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($formModifier) {
                $formModifier($event->getForm());
            }
        );

        $builder->get('measure')->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) use ($formModifier) {
                $project = $event->getForm()->getParent()->getData();
                $measure = $event->getForm()->getData();

                if ($measure) {
                    foreach ($measure->getMeasureValues() as $measureValue) {
                        $projectMeasureValue = new ProjectMeasureValue($measureValue);
                        $project->addProjectMeasureValue($projectMeasureValue);
                    }
                } else {
                    $project->clearProjectMeasureValues();
                }

                $formModifier($event->getForm()->getParent());
            }
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/AppBundle/Controller/ProjectController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Project;
use AppBundle\Form\ProjectType;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class ProjectController extends Controller
{
    /**
     * @Route("/", name="project_register")
     * @Template()
     */
    public function registerAction(Request $request, EntityManagerInterface $em)
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $project = $form->getData();

            $em->persist($project);
            $em->flush();

            return $this->redirectToRoute('project_show', [
                'project' => $project->getId(),
            ]);
        }

        return [
            'form' => $form->createView(),
        ];
    }

    /**
     * @Route("/show/{project}", name="project_show")
     * @Template()
     */
    public function showAction(Project $project): array
    {
        return [
            'project' => $project,
        ];
    }

    /**
     * @Route("/details/{project}", name="project_details")
     * @Template()
     */
    public function detailsAction(Project $project): array
    {
        return [
            'project' => $project,
        ];
    }

    /**
     * @Route("/{project}/pdf", name="project_pdf")
     */
    public function pdfAction(
        Project $project,
        Pdf $pdfGenerator
    ): PdfResponse {
        $html = $this->render('@App/project/pdf.html.twig', ['project' => $project,]);

        return new PdfResponse(
            $pdfGenerator->getOutputFromHtml($html),
            'project.pdf'
        );
    }
}

src/AppBundle/Resources/views/project/details.html.twig
{% extends '@App/base.html.twig' %}

{% from '@App/macro/fields.html.twig' import baseField %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="tabs-container">
                <div class="tab-content">
                    <div class="tab-pane active">
                        <div class="panel-body">
                            <fieldset>
                                {{ baseField('Id', project.id) }}
                                {{ baseField('Pildymo data', project.createdAt|date('Y-m-d')) }}
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/project/pdf.html.twig
{{ barcode({code: project.qrCode, type: 'qrcode', format: 'html'}) }}

src/AppBundle/Resources/views/project/register.html.twig
{% extends '@App/base.html.twig' %}

{% form_theme form '@App/theme/form_errors.html.twig' %}

{% from '@App/macro/formFields.html.twig' import baseField, measureField %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel-body">

                        {{ form_start(form) }}

                        <fieldset>

                            {{ baseField(form.user.firstName) }}
                            {{ baseField(form.user.lastName) }}
                            {{ baseField(form.user.address) }}
                            {{ baseField(form.user.email) }}
                            {{ baseField(form.user.phone) }}
                            {{ baseField(form.user.houseNumber) }}
                            {{ baseField(form.user.hasCompensation) }}

                            {{ baseField(form.measure) }}

                            <div id="project_measureValues">
                                {% for projectMeasureValue in form.projectMeasureValues %}
                                    {{ measureField(projectMeasureValue) }}
                                {% endfor %}
                            </div>

                            {{ baseField(form.createdAt) }}

                            <hr>

                            <button class="btn btn-primary float-right">Registruoti</button>

                        </fieldset>

                        {{ form_end(form) }}

                        <div class="alert alert-warning mt-3">
                            <strong>Informacija</strong>
                            <p>Čia pateikiama informacija apie pareiškėjų prisiimamus įsipareigojimus.</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/AppBundle/Resources/views/project/show.html.twig
{% extends '@App/base.html.twig' %}

{% from '@App/macro/fields.html.twig' import moneyField %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="panel-body">

                        <fieldset>

                            {% for measure in project.projectMeasureValues %}
                                {{ moneyField(measure.name, measure.rate) }}
                            {% endfor %}

                            {{ moneyField('Suma', project.totalRate) }}

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <a href="{{ path('project_pdf', {'project': project.id}) }}" class="btn btn-primary">PDF</a>
                                </div>
                            </div>

                        </fieldset>

                        <div class="alert alert-warning mt-3">
                            <p>Nebuvo pateika formulė, kaip apskaičiuoti investicijų sumą.
                               Atvaizduoju priemonių tarifus ir jų bendrą sumą.
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}